{% set name = "nltk" %}
{% set version = "3.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed03bc098a40481310320808b2db712d95d13ca65b27372f8a403949c8b523d0

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - nltk = nltk.cli:cli

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click
    - joblib
    - regex >=2021.8.3
    - tqdm

# Tests which are using external resources:
# E         Resource 'x' not found. Please use the NLTK Downloader to obtain the resource:
# E         >>> import nltk
# E         >>> nltk.download('x')
{% set ignore_tests = " --ignore=nltk/test/unit/test_brill.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_cfd_mutation.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_cfg2chomsky.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_corpus_views.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_pl196x.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_pos_tag.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_rte_classify.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_stem.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_tokenize.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_wordnet.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/translate/test_bleu.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/translate/test_nist.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_concordance.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_json2csv_corpus.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_corpora.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_nombank.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_json_serialization.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/translate/test_meteor.py" %}
{% set ignore_tests = ignore_tests + " --ignore=nltk/test/unit/test_tag.py" %}

test:
  source_files:
    - nltk/test
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.lm
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter
  requires:
    - pip
    # tqdm and click requires colorama
    - colorama  # [win]
    - pytest >=6.0.1
    - numpy
    - pytest-mock
    - pyparsing
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v nltk/test {{ ignore_tests }} -k "not doctest"
    - nltk -h

about:
  home: https://www.nltk.org
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Natural Language Toolkit
  description: |
    NLTK has been called a wonderful tool for teaching and working in
    computational linguistics using Python and an amazing library to play with
    natural language.
  dev_url: https://github.com/nltk/nltk
  doc_url: https://www.nltk.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - quartox
