{% set name = "nltk" %}
{% set version = "3.4.4" %}
{% set bundle = "zip" %}
{% set hash_type = "sha256" %}
{% set hash = "764c20a5f8532a681c261af3c7d1a54768a35df6f3603df75e615cbd34e47cb5" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - setuptools
    - unzip

  run:
    - python
    - six
    - gensim
    - numpy
    - python-crfsuite
    - scikit-learn
    - scipy
    - matplotlib
    - pyparsing
    - twython
    - requests

test:
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter

about:
  home: http://nltk.org/
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Natural Language Toolkit'
  dev_url: https://github.com/nltk/nltk
  doc_url: http://www.nltk.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - quartox
