{% set version = "3.6.5" %}

package:
  name: nltk
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nltk/nltk-{{ version }}.zip
  sha256: 834d1a8e38496369390be699be9bca4f2a0f2175b50327272b2ec7a98ffda2a0

build:
  number: 0
  skip: True  # [py<36]
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - nltk = nltk.cli:cli

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - click
    - joblib
    - regex >=2021.8.3
    - tqdm

test:
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.lm
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter
  requires:
    - python <3.10
    - pip
    # tqdm and click requires colorama
    - colorama  # [win]
  commands:
    - pip check
    - nltk -h

about:
  home: http://nltk.org/
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Natural Language Toolkit'
  description: |
    NLTK has been called a wonderful tool for teaching and working in
    computational linguistics using Python and an amazing library to play with
    natural language.
  doc_source_url: https://github.com/nltk/nltk/blob/develop/web/index.rst
  dev_url: https://github.com/nltk/nltk
  doc_url: http://www.nltk.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - quartox
