{% set version = "3.4.1" %}

package:
  name: nltk
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nltk/nltk-{{ version }}.zip
  sha256: 3a64b1cb685bbf344adec416871fee07996671c876ff313b3e504158fa1500e1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six
    - singledispatch  # [py27]

test:
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter

about:
  home: http://nltk.org/
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: Build Python programs to work with human language data
  description: |
    NLTK has been called a wonderful tool for teaching and working in
    computational linguistics using Python and an amazing library to play with
    natural language.
  doc_url: https://nltk.readthedocs.io/en/latest/
  doc_source_url: https://github.com/nltk/nltk/blob/develop/web/index.rst
  dev_url: https://github.com/nltk/nltk

extra:
  recipe-maintainers:
    - pmlandwehr
