travis:
  secure:
    BINSTAR_TOKEN: rdIyyVFOpgnZYa1l3ceLW47siTDUoKXd3i/GnzgkjdefGrM1/Vkl6VwUkuz+TXifcGBJOti3nziQoa0gbsuUUduYi7LtwOiR5BJezODgJafzpFiI6AA65pjalIT8sGdIc5DQoPKeoXmWB2y2iXPTKCtENUZL87bZKfoD+q3T+669bS88G9WREQQMKUupBJmVr8GQiNi6ZRU2mA+cGTDVA8VktU/m4RgGK+FnhYvBuhMwTE/6QhwgdTl7Iv4zkk2Wr61f9GVfCkthdg4NxKj0TNG6Lc4thXi9j7AdwsufoqPOYdp3LJHrq7KDNQ6UICmI9clSRxmg28A7XYeU5vjTXyreY2UoLXZqk7vftpmqhCJ/mVWCPWMF6XTBB8na5XT9oXzNeyAu+nfglLVvxW8MzCa2etsZBzmkYnvhqr+g4I4UVz4rgzrBVyQiNN7spMk7f1J1njYUjMQvc5L7yxdS+J6AENnxoEP6DNsn6HhPIZvpWBaalY000w68zhq4Zi2H65edc0k0H9Q45JkQC/OA/IaOKJHxAaq/uYSZj8fn4eJ7QTJ3OsHSOib+6267UWWhFY12kmIzjTytotHodCUgNYgJgmgJ4Vv1Wi01JIVbu3tMU1ETGOqdqEZwvC/MJmqkCx5yljdVcESVKUcslQnLoLOVmDpl+Y5BX39K5pkWXxk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
