travis:
  secure:
    BINSTAR_TOKEN: qbcYvk12NiDqohs0OmhJJWCOLchdjSQEavTbDiguOLVhn7bJow/IwLSTKGhrX+JB2f0jmbb/6DVZxD7eESGXEN11xcmjyr9Gihma1IJ5kYvM8vIUnUgQ68hyWLM8xuWlvzMEuTowOFzu7iPIEmlxDre2viRyPwH4i5G4q4xeyxHkAoMv9Lqns2qOZWSz1FgG1CsUTFzpTpLJLmT9bTuLjoQYTX4KPKBYCksK7R29QL7Tp7qK71pOhvxBFTlyjixbahjy9rW3ROR8Sb31ZsvDP/1/JV2wg2XTaWk99uX3GetriVm6ftGx4m/JUCx+8Nig4kaN8MeeYuVW77ilDIQPmXfImukRZR1HXdoT4iG2EUbEUJv24OI+d0uxZKtOdqiFh3BDD3u4r9vOyXjWZH6nTOsT8eettSrM/oYREaIcBecJ1MyFo/4PFb5+8XOsZoEPQ9lhpVFxLgbYq4OGiZ139D4zv7+SBlnFmNG9rzl4EV6MyKBaUMkHm00i7Z6zCTeEat4BsjmaiwHIlYOKGoMoDmFlIwQXEJECDOBB95Amr4Nb+2Dh98EGmnGtGXyiDBeNGuhXYhHvGoK5NdIjdz+37EijJweDG/1lrovzZ361iZ3co2qBNIZnHv2RprzuTwM7QrWjuK7LC1UCoE9fTR6XTdRlPHvYDFysjep9BvXPrps=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
